name: Test

on:
  push:
    branches:
      - master
  pull_request: {}
  merge_group: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        protoc_version:
          - "3.18.2"
          - "3.19.4"
          - "24.4"
          - "25.2"
    name: test (ruby=${{ matrix.ruby }}, protoc=${{ matrix.protoc_version }})
    steps:
      - name: Install protoc
        run: |
          cd /tmp
          sudo apt-get update
          sudo apt-get -y install curl unzip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${{ matrix.protoc_version }}/protoc-${{ matrix.protoc_version }}-linux-x86_64.zip
          unzip protoc-${{ matrix.protoc_version }}-linux-x86_64.zip
          sudo mv bin/protoc /usr/local/bin/protoc
          protoc --version
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler: none
      - name: Set up git safe.directory
        run: |
          git config --global --add safe.directory /__w/rbs_protobuf/rbs_protobuf
      - name: Run test
        run: |
          ruby -v
          gem install bundler
          bin/setup
          bundle exec rake
          bundle exec rake install
