name: Test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        container_tag:
          - 3.0-dev-focal
          - 3.1-dev-jammy
          - 3.2-dev-jammy
        protoc_version:
          - "3.18.2"
          - "3.19.4"
          - "24.0"
    container:
      image: rubylang/ruby:${{ matrix.container_tag }}
    steps:
      - name: Install protoc
        run: |
          cd /tmp
          apt-get update
          apt-get -y install curl unzip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v${{ matrix.protoc_version }}/protoc-${{ matrix.protoc_version }}-linux-x86_64.zip
          unzip protoc-${{ matrix.protoc_version }}-linux-x86_64.zip
          mv bin/protoc /usr/local/bin/protoc
          protoc --version
      - uses: actions/checkout@v3
      - name: Set up git safe.directory
        run: |
          git config --global --add safe.directory /__w/rbs_protobuf/rbs_protobuf
      - name: Run test
        run: |
          ruby -v
          gem install bundler
          bin/setup
          bundle exec rake
          bundle exec rake install
